$apps = @(
    "7zip"
    "bulkrenameutility"
    "caddy"
    "calibre"
    "chocolateygui"
    "deluge"
    "discord"
    "ditto"
    "docker-toolbox"
    "etcher"
    "ffmpeg"
    "filezilla"
    "firefox"
    "freefilesync"
    "git"
    "googlechrome"
    "greenshot"
    "imgburn"
    "keepass"
    "mpc-be"
    "notepadplusplus"
    "obs-studio"
    "openssh -params /SSHAgentFeature"
    "packer"
    "python --version 3.7.2"
    "steam"
    "sumatrapdf"
    "sysinternals"
    "taiga"
    "teracopy"
    "uplay"
    "veeam-agent"
    "visualstudiocode"
    "vmwareworkstation"
    "vnc-connect"
    "vnc-viewer"
)

foreach ($app in $apps) { choco.exe install $app }
