$apps = @(
    "7zip"
    "bulkrenameutility"
    "calibre"
    "deluge"
    "discord"
    "ditto"
    "etcher"
    "ffmpeg"
    "filezilla"
    "firefox"
    "freefilesync"
    "git"
    "googlechrome"
    "greenshot"
    "imgburn"
    "keepass"
    "mpc-be"
    "notepadplusplus"
    "obs-studio"
    "openssh -params /SSHAgentFeature"
    "python --version 3.6.5"
    "steam"
    "sumatrapdf"
    "sysinternals"
    "taiga"
    "teracopy"
    "thunderbird"
    "uplay"
    "veeam-agent"
    "visualstudiocode"
    "vlc"
    "vmware-horizon-client"
    "vmwareworkstation"
    "vnc-connect"
    "vnc-viewer"
    "whatsapp"
)

foreach ($app in $apps) { choco install $app }
