$apps = @(
    "7zip.install"
    "authy-desktop"
    "audacity"
    "audacity-lame"
    "bitwarden"
    "bulkrenameutility.install"
    "caddy"
    "calibre"
    "chocolateygui"
    "deluge"
    "discord.install"
    "ditto"
    "docker-toolbox"
    #"dropbox"
    #"eac"
    "etcher"
    "ffmpeg"
    "filezilla"
    "firefox"
    #"freefilesync"
    "git.install"
    #"google-backup-and-sync"
    "googlechrome"
    "greenshot"
    "imgburn"
    "keepass.install"
    "mailspring"
    "mpc-be"
    "notepadplusplus.install"
    "obs-studio"
    #"open-shell"
    "openssh -params /SSHAgentFeature"
    "packer"
    #"playnite"
    "plexmediaserver"
    #"python --version 3.7.2"
    #"spotify"
    #"steam"
    "sumatrapdf.commandline"
    "sysinternals"
    "taiga"
    "teracopy"
    #"ums"
    #"uplay"
    "veeam-agent"
    "visualstudiocode"
    "vmware-horizon-client"
    "vmwareworkstation"
    "vnc-connect"
    "vnc-viewer"
    #"winauth"
    #"wsl"
    #"yumi"
)

foreach ($app in $apps) { choco.exe install -y $app }
